trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'ANy CPU'
  buildConfiguration: 'Release'
  solution: '*/mysolution.sln.sln'
  project: '**/*.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'Nuget tool installer'

- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'Nuget restore package'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'Tests'
  displayName: 'run tests'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.cs'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
